feat(security): treat negotiation succeed if server is old version
XiaoMi/pegasus-java-client pull request #145
Opened 2020-12-18 10:43 UTC by levy5307

if the is new version with authentication and it enables it, and server is old version, which doesn't has the rpc code `RPC_NEGOTIATION`. so the client will sends negotiation message when it starts. And server will return error `ERR_HANDLER_NOT_FOUND`, and then the session will be reset.

Same with the situation which server disables authentication. In this case, the server will return `negotiation_status.SASL_AUTH_DISABLE`to client.

2020-12-18 11:02 UTC, Shuo-Jia approved these changes

2020-12-18 11:06 UTC, neverchanje requested changes

2020-12-18 11:06 UTC, neverchanje commented on src/main/java/com/xiaomi/infra/pegasus/security/Negotiation.java
> +          // ERR_HANDLER_NOT_FOUND means server is old version, which doesn't support authentication
```suggestion
          // ERR_HANDLER_NOT_FOUND means server is old version, which doesn't support authentication
          // In this case we consider this session will expose no privacy at all, so we can just
          // go on without negotiation.
```

2020-12-18 11:06 UTC, neverchanje commented on src/main/java/com/xiaomi/infra/pegasus/security/Negotiation.java
> +          }
```suggestion
          }
          throw new ReplicationException(op.rpc_error.errno);
```

2020-12-18 11:09 UTC, neverchanje approved these changes

2020-12-29 10:00 UTC, Shuo-Jia approved these changes

2020-12-29 10:01 UTC, merged